<?php echo $this->doctype() ?>
<html>
<head>
    <?php echo $this->headMeta()->appendHttpEquiv('Content-Type',
                                                  'text/html; charset=UTF-8')?>
    <?php echo $this->headTitle()?>
    <?php echo $this->headLink()?>
    <?php echo $this->headScript()?>

</head>
<body>
    <div id="wrapper">
        <?php echo $this->layout()->header;?>				
        <?php //include_once('application/views/includes/message.php');?>
        <?php echo $this->layout()->content ?>        		
        <?php echo $this->layout()->footer;?>					
    </div><!-- END wrapper   -->
    
    <?php echo $this->inlineScript()?>
    
</body>
</html>