<!-- application/views/scripts/error/error.phtml -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN";
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Zend Framework Default Application</title>
</head>
<body>
  <h1>An error occurred</h1>
  <div><?php echo $this->message?></div>
  <?php if ( 'development' == $this->env ): ?>
  <h3>Exception Information</h3>
  <div>
      <b>Message:</b> <?php echo $this->exception->getMessage()?>
  </div>
  <div>
      <b>Trace:</b> <?php echo $this->exception->getTraceAsString()?>
  </div>
  <div>
      <b>Request:</b> <?php vardump($this->request->getParams())?>
  </div>
  
  <?php endif ?>
</body>
</html>